fn main() {
    #[cfg(feature = "cbindgen")]
    {
        let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let config = cbindgen::Config {
            language: cbindgen::Language::C,
            include_guard: Some("SPIF_H".to_string()),
            autogen_warning: Some(
                "/* Auto-generated by cbindgen — DO NOT EDIT. */\n/* Source: spif-rust/src/ffi.rs */".to_string(),
            ),
            ..Default::default()
        };

        cbindgen::Builder::new()
            .with_crate(crate_dir)
            .with_config(config)
            .generate()
            .expect("cbindgen failed to generate header")
            .write_to_file("include/spif.h");
    }

    // Also regenerate on ffi.rs changes
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=src/types.rs");
}
