#!/usr/bin/env bash
# Cross-implementation compatibility test.
# Generates deterministic SPIF fixtures with Python, reads each with the
# TypeScript reader, and compares key fields against Python-generated refs.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TMPDIR="$(mktemp -d)"
PASS=0
FAIL=0

cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT

echo "Cross-implementation compatibility test"
echo "Python → Deno SPIF reader"
echo "=================================="

# Generate reference files using Python
${PYTHON3:-python3} "$SCRIPT_DIR/generate_compat_fixtures.py" "$TMPDIR"

# Determinism check: regenerated bytes must match the committed fixture corpus
COMMITTED_DIR="$PROJECT_DIR/spfx/fixtures/cross_lang"
if [[ -d "$COMMITTED_DIR" ]]; then
  DETERMINISM_FAIL=0
  for committed_file in "$COMMITTED_DIR"/*.spfx; do
    name="$(basename "$committed_file")"
    regenerated="$TMPDIR/$name"
    if [[ ! -f "$regenerated" ]]; then
      echo "DETERMINISM FAIL: $name missing from regenerated output"
      DETERMINISM_FAIL=1
      continue
    fi
    if ! cmp -s "$committed_file" "$regenerated"; then
      echo "DETERMINISM FAIL: $name differs from committed fixture"
      DETERMINISM_FAIL=1
    fi
  done
  if [[ "$DETERMINISM_FAIL" -eq 0 ]]; then
    echo "Determinism check: regenerated bytes match committed fixtures — PASS"
  else
    echo "Determinism check: FAILED (see above)"
    exit 1
  fi
else
  echo "SKIP determinism check: $COMMITTED_DIR not present"
fi

# Check Deno is available
if ! command -v deno &>/dev/null; then
  echo "SKIP: Deno not installed. Install with: brew install deno"
  echo "      Then re-run this script."
  exit 0
fi

# Read each file with both Python and Deno, compare key fields
for spif_file in "$TMPDIR"/*.spfx; do
  name="$(basename "$spif_file" .spfx)"
  ref_json="$TMPDIR/${name}.ref.json"

  if [[ ! -f "$ref_json" ]]; then
    echo "SKIP $name (no reference JSON)"
    continue
  fi

  # Read with Deno TS reader
  ts_json="$TMPDIR/${name}.ts.json"
  if deno run --allow-read "$SCRIPT_DIR/sif_reader.ts" "$spif_file" > "$ts_json" 2>/dev/null; then
    # Compare payload_count and trace_count
    ref_payload=$(${PYTHON3:-python3} -c "import json; d=json.load(open('$ref_json')); print(d['payload_count'])")
    ts_payload=$(${PYTHON3:-python3} -c "import json; d=json.load(open('$ts_json')); print(d['payload_count'])")

    ref_trace=$(${PYTHON3:-python3} -c "import json; d=json.load(open('$ref_json')); print(d['trace_count'])")
    ts_trace=$(${PYTHON3:-python3} -c "import json; d=json.load(open('$ts_json')); print(d['trace_count'])")

    ref_model=$(${PYTHON3:-python3} -c "import json; d=json.load(open('$ref_json')); print(d.get('source_model') or 'null')")
    ts_model=$(${PYTHON3:-python3} -c "import json; d=json.load(open('$ts_json')); p=d.get('provenance'); print(p['source_model'] if p else 'null')")

    if [[ "$ref_payload" == "$ts_payload" ]] && \
       [[ "$ref_trace" == "$ts_trace" ]] && \
       [[ "$ref_model" == "$ts_model" ]]; then
      echo "PASS $name  (payload=$ts_payload, trace=$ts_trace, model=$ts_model)"
      PASS=$((PASS + 1))
    else
      echo "FAIL $name"
      echo "  payload: expected=$ref_payload got=$ts_payload"
      echo "  trace:   expected=$ref_trace   got=$ts_trace"
      echo "  model:   expected=$ref_model   got=$ts_model"
      FAIL=$((FAIL + 1))
    fi
  else
    echo "FAIL $name (Deno reader errored)"
    FAIL=$((FAIL + 1))
  fi
done

echo "=================================="
echo "Results: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
