name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    paths:
      - 'spif-py/**'
      - '.clusterfuzzlite/**'
permissions: read-all
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: python
      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          fuzz-seconds: 300
          mode: 'code-change'
          sanitizer: address
          output-sarif: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
